server:
  port: 8088
  servlet:
    contextPath: /security
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/foodgood?user=root
    driverClassName: com.mysql.cj.jdbc.Driver